FROM python:3.11-slim

WORKDIR /app

# ‰”Œ „ ÿ·»«  Python √Ê·«
COPY requirements.txt .

#  À»Ì  «·„ ÿ·»« 
RUN pip install --no-cache-dir -r requirements.txt

# ‰”Œ »«ﬁÌ «·ﬂÊœ
COPY . .

#  ‘€Ì· «·„·› «·’ÕÌÕ - ·Ì” app.py
CMD ["python", "unified.py"]

# ﬂ‘› «·„‰›–
EXPOSE 8080