name: Manual workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all files in directory
        run: ls -la

      - name: Run Python script
        run: python run.py.txt
